In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
train = pd.read_csv("train_HFxi8kT/train.csv")
campaign_data = pd.read_csv("train_HFxi8kT/campaign_data.csv")
test = pd.read_csv("test_BDIfz5B.csv/test_BDIfz5B.csv")

In [3]:
sample_submission = pd.read_csv("sample_submission_4fcZwvQ.csv")

In [4]:
train.head()

id  user_id  campaign_id         send_date  is_open  is_click
0   42_14051    14051           42  01-09-2017 19:55        0         0
1  52_134438   134438           52  02-11-2017 12:53        0         0
2  33_181789   181789           33  24-07-2017 15:15        0         0
3  44_231448   231448           44  05-09-2017 11:36        0         0
4  29_185580   185580           29  01-07-2017 18:01        0         0

In [5]:
test.head()

id  campaign_id  user_id         send_date
0  63_122715           63   122715  01-02-2018 22:35
1   56_76206           56    76206  02-01-2018 08:15
2   57_96189           57    96189  05-01-2018 18:25
3  56_166917           56   166917  02-01-2018 08:15
4  56_172838           56   172838  02-01-2018 08:12

In [6]:
campaign_data.head()


campaign_id communication_type  total_links  no_of_internal_links  \
0           29         Newsletter           67                    61   
1           30    Upcoming Events           18                    14   
2           31         Conference           15                    13   
3           32         Conference           24                    19   
4           33             Others            7                     3   

   no_of_images  no_of_sections  \
0            12               3   
1             7               1   
2             5               1   
3             7               1   
4             1               1   

                                          email_body  \
0  Dear AVians,\r\n \r\nWe are shaping up a super...   
1  Dear AVians,\r\n \r\nAre your eager to know wh...   
2  Early Bird Pricing Till August 07 – Save upto ...   
3  \r\n \r\nHi ?\r\n \r\nBefore I dive into why y...   
4  Fireside Chat with DJ Patil - the master is he...   

                                             subject  \
0  Sneak Peek: A look at the emerging data scienc...   
1  [July] Data Science Expert Meetups & Competiti...   
2  Last chance to convince your boss before the E...   
3  A.I. & Machine Learning: 5 reasons why you sho...   
4  [Delhi NCR] Fireside Chat with DJ Patil, Forme...   

                                           email_url  
0  http://r.newsletters.analyticsvidhya.com/7um44...  
1  http://r.newsletters.analyticsvidhya.com/7up0e...  
2  http://r.newsletters.analyticsvidhya.com/7usym...  
3  http://r.newsletters.analyticsvidhya.com/7uthl...  
4  http://r.newsletters.analyticsvidhya.com/7uvlg...

In [7]:
sample_submission.head()

id  is_click
0  63_122715         0
1   56_76206         0
2   57_96189         0
3  56_166917         0
4  56_172838         0

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1023191 entries, 0 to 1023190
Data columns (total 6 columns):
id             1023191 non-null object
user_id        1023191 non-null int64
campaign_id    1023191 non-null int64
send_date      1023191 non-null object
is_open        1023191 non-null int64
is_click       1023191 non-null int64
dtypes: int64(4), object(2)
memory usage: 46.8+ MB


In [9]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 773858 entries, 0 to 773857
Data columns (total 4 columns):
id             773858 non-null object
campaign_id    773858 non-null int64
user_id        773858 non-null int64
send_date      773858 non-null object
dtypes: int64(2), object(2)
memory usage: 23.6+ MB


In [10]:
campaign_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 9 columns):
campaign_id             52 non-null int64
communication_type      52 non-null object
total_links             52 non-null int64
no_of_internal_links    52 non-null int64
no_of_images            52 non-null int64
no_of_sections          52 non-null int64
email_body              52 non-null object
subject                 52 non-null object
email_url               52 non-null object
dtypes: int64(5), object(4)
memory usage: 3.7+ KB


In [11]:
train.campaign_id.unique()

array([42, 52, 33, 44, 29, 49, 30, 54, 36, 53, 32, 48, 50, 41, 47, 39, 34,
       46, 35, 31, 37, 38, 45, 51, 40, 43])

In [12]:
campaign_data.campaign_id.unique()

array([29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
       63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
       80])

In [13]:
test.campaign_id.unique()


array([63, 56, 57, 71, 76, 74, 67, 75, 64, 69, 78, 79, 61, 58, 77, 60, 80,
       65, 70, 55, 68, 73, 59, 66, 72, 62])

In [14]:
df_train = pd.merge(train, campaign_data, how='left', on='campaign_id', left_on=None, right_on=None,
                          left_index=False, right_index=False, sort=True,
                          suffixes=('_x', '_y'), copy=True, indicator=False)


In [15]:
df_train.head(3)

id  user_id  campaign_id         send_date  is_open  is_click  \
0  29_185580   185580           29  01-07-2017 18:01        0         0   
1  29_103665   103665           29  01-07-2017 18:05        0         0   
2  29_219721   219721           29  01-07-2017 18:04        0         0   

  communication_type  total_links  no_of_internal_links  no_of_images  \
0         Newsletter           67                    61            12   
1         Newsletter           67                    61            12   
2         Newsletter           67                    61            12   

   no_of_sections                                         email_body  \
0               3  Dear AVians,\r\n \r\nWe are shaping up a super...   
1               3  Dear AVians,\r\n \r\nWe are shaping up a super...   
2               3  Dear AVians,\r\n \r\nWe are shaping up a super...   

                                             subject  \
0  Sneak Peek: A look at the emerging data scienc...   
1  Sneak Peek: A look at the emerging data scienc...   
2  Sneak Peek: A look at the emerging data scienc...   

                                           email_url  
0  http://r.newsletters.analyticsvidhya.com/7um44...  
1  http://r.newsletters.analyticsvidhya.com/7um44...  
2  http://r.newsletters.analyticsvidhya.com/7um44...

In [16]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1023191 entries, 0 to 1023190
Data columns (total 14 columns):
id                      1023191 non-null object
user_id                 1023191 non-null int64
campaign_id             1023191 non-null int64
send_date               1023191 non-null object
is_open                 1023191 non-null int64
is_click                1023191 non-null int64
communication_type      1023191 non-null object
total_links             1023191 non-null int64
no_of_internal_links    1023191 non-null int64
no_of_images            1023191 non-null int64
no_of_sections          1023191 non-null int64
email_body              1023191 non-null object
subject                 1023191 non-null object
email_url               1023191 non-null object
dtypes: int64(8), object(6)
memory usage: 117.1+ MB


In [17]:
df_test = pd.merge(test, campaign_data, how='left', on='campaign_id', left_on=None, right_on=None,
                          left_index=False, right_index=False, sort=True,
                          suffixes=('_x', '_y'), copy=True, indicator=False)

In [18]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 773858 entries, 0 to 773857
Data columns (total 12 columns):
id                      773858 non-null object
campaign_id             773858 non-null int64
user_id                 773858 non-null int64
send_date               773858 non-null object
communication_type      773858 non-null object
total_links             773858 non-null int64
no_of_internal_links    773858 non-null int64
no_of_images            773858 non-null int64
no_of_sections          773858 non-null int64
email_body              773858 non-null object
subject                 773858 non-null object
email_url               773858 non-null object
dtypes: int64(6), object(6)
memory usage: 76.8+ MB


In [19]:
df_train.communication_type.unique()

array(['Newsletter', 'Upcoming Events', 'Conference', 'Others', 'Webinar',
       'Corporate', 'Hackathon'], dtype=object)

In [20]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(np.hstack([df_train.communication_type, df_test.communication_type]))
df_train.communication_type = le.transform(df_train.communication_type)
df_test.communication_type = le.transform(df_test.communication_type)
del le

df_train.head(3)


id  user_id  campaign_id         send_date  is_open  is_click  \
0  29_185580   185580           29  01-07-2017 18:01        0         0   
1  29_103665   103665           29  01-07-2017 18:05        0         0   
2  29_219721   219721           29  01-07-2017 18:04        0         0   

   communication_type  total_links  no_of_internal_links  no_of_images  \
0                   3           67                    61            12   
1                   3           67                    61            12   
2                   3           67                    61            12   

   no_of_sections                                         email_body  \
0               3  Dear AVians,\r\n \r\nWe are shaping up a super...   
1               3  Dear AVians,\r\n \r\nWe are shaping up a super...   
2               3  Dear AVians,\r\n \r\nWe are shaping up a super...   

                                             subject  \
0  Sneak Peek: A look at the emerging data scienc...   
1  Sneak Peek: A look at the emerging data scienc...   
2  Sneak Peek: A look at the emerging data scienc...   

                                           email_url  
0  http://r.newsletters.analyticsvidhya.com/7um44...  
1  http://r.newsletters.analyticsvidhya.com/7um44...  
2  http://r.newsletters.analyticsvidhya.com/7um44...

In [21]:
predictors = df_train[["user_id", "campaign_id", "communication_type", "total_links","no_of_internal_links", "no_of_images",
                   "no_of_sections"]]
y = df_train["is_click"]

In [22]:

from sklearn.model_selection import cross_val_score
from xgboost import XGBClassifier

model = XGBClassifier()



/home/shahir/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [23]:
scores = cross_val_score(model, predictors, y, scoring='roc_auc', cv=5)
print(scores)


[ 0.48013887  0.50427563  0.40323038  0.46834917  0.47934604]


In [24]:
print('Mean ROC_AUC %2f' %(1 * scores.mean()))

Mean ROC_AUC 0.467068


In [25]:
test_predictors = df_test[["user_id", "campaign_id", "communication_type", "total_links","no_of_internal_links", "no_of_images",
                   "no_of_sections"]]

In [26]:

model.fit(predictors, y, verbose=False)



XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=1,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

In [27]:
prediction = model.predict(test_predictors)
print(prediction)

[0 0 0 ..., 0 0 0]


In [28]:

my_submission = pd.DataFrame({'id': test.id, 'is_click': prediction})
my_submission.to_csv('XG_submission.csv', index=False)

In [29]:
my_submission

id  is_click
0       63_122715         0
1        56_76206         0
2        57_96189         0
3       56_166917         0
4       56_172838         0
5        71_50253         0
6       76_128244         0
7       74_195513         0
8        67_74617         0
9       75_140599         0
10      63_124394         0
11       63_95168         0
12       74_90706         0
13       63_31556         0
14      57_166505         0
15        64_2089         0
16      74_133849         0
17        74_7486         0
18      57_159015         0
19      64_111872         0
20      56_176763         0
21        71_8316         0
22      69_133308         0
23       74_50984         0
24       76_64692         0
25      64_184811         0
26       57_81487         0
27       57_41624         0
28       71_95059         0
29       71_25044         0
...           ...       ...
773828   56_47638         0
773829  57_199696         0
773830  56_162289         0
773831  69_145085         0
773832  74_233054         0
773833   63_42227         0
773834  74_238916         0
773835   64_67184         0
773836   63_64538         0
773837   71_83603         0
773838   57_13091         0
773839  63_216162         0
773840  63_111877         0
773841  63_163766         0
773842   74_40948         0
773843   74_59284         0
773844  64_232176         0
773845   69_65847         0
773846  76_200174         0
773847  57_191488         0
773848   69_42153         0
773849  57_127883         0
773850  55_153170         0
773851    57_4034         0
773852   74_80370         0
773853  74_202929         0
773854   56_95437         0
773855   63_11063         0
773856  72_144182         0
773857  57_226299         0

[773858 rows x 2 columns]